---
title: "Linear Regression"
output: github_document
---

```{r setup,include=FALSE}
library(tidyverse)
library(modelr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =0.6,
  out.width = "90%"
) 

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1
```{r,warning=FALSE}
birth_w = read_csv("./birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
        babysex = factor(babysex),
        babysex = fct_recode(babysex,"Male"="1", "Female"= "2"),
        frace =factor(frace),
        frace = fct_recode(frace,"White"="1","Black"="2","Asian"="3","Puerto Rican" = "4","Other"="8","Unknown"="9"),
        malform =factor(malform),
        malform =fct_recode(malform,"absent"="0","present"="1"),
        mrace=factor(mrace),
        mrace = fct_recode(mrace,"White"="1","Black"="2","Asian"="3","Puerto Rican" = "4","Other"="8")) %>% 
  na.omit()
```

```{r}
rl = lm(bwt~blength,data = birth_w)

birth_w %>% 
  modelr::add_predictions(rl) %>% 
  ggplot(aes(x = pred, y = bwt)) + geom_point()+
  labs(
     x="Predicted Values",
     y="Actual Values",
     title =" Predicted vs. Actual Values")


birth_w %>% 
  modelr::add_residuals(rl) %>% 
  ggplot(aes(x = blength, y = resid)) + geom_point()
```

#### using length at birth and gestational age as predictors
```{r}
fit = lm(bwt ~ blength + gaweeks, data = birth_w)
fit %>% 
  broom::tidy()

birth_w %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x=blength,y=resid))+
  geom_point()


birth_w %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x=gaweeks,y=resid))+
  geom_point()+
  facet_wrap(.~blength)
```


## Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

 